<a href="https://colab.research.google.com/github/tkalra11/PyTorch_FCC/blob/master/00_pytorch_fundamentals_run.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundaamentals

In [1]:
import numpy as np
import pandas as pd
import torch

In [2]:
some_tensor = torch.rand((3,4))

In [3]:
print(some_tensor)
print(f"Datatype of the tensor : {some_tensor.dtype}")
print(f"Shape of the tensor :  {some_tensor.shape}")
print(f"Device the tensor is on  : {some_tensor.device}")

tensor([[0.7610, 0.9172, 0.1563, 0.8420],
        [0.0133, 0.5007, 0.6630, 0.0950],
        [0.9425, 0.8204, 0.5240, 0.7089]])
Datatype of the tensor : torch.float32
Shape of the tensor :  torch.Size([3, 4])
Device the tensor is on  : cpu


### Tensor operations :

*   Addition
*   Subtraction
*   Element wise multiplication
*   Division
*   Matrix Multiplication

In [4]:
#Creating a tensor
tensor = torch.tensor([1,2,3])

In [5]:
#Addition
tensor + 10

tensor([11, 12, 13])

In [6]:
#Subtraction
tensor - 1

tensor([0, 1, 2])

In [7]:
#Element wise multiplication
tensor  * 10

tensor([10, 20, 30])

In [8]:
#Division
tensor / 5

tensor([0.2000, 0.4000, 0.6000])

In [9]:
#inbuilt functions

torch.add(tensor,10)

tensor([11, 12, 13])

In [10]:
torch.mul(tensor,10)

tensor([10, 20, 30])

### Matrix multiplication

Details => https://www.mathsisfun.com/algebra/matrix-multiplying.html

Rules :

1. The **inner dimensions** must match:
*   `(3,2) @ (3,2)` won't work
*   `(2,3) @ (3,2)` will work
2.  The resulting matrix has the shape of the **outer dimensions**:
*   `(2,3) @ (3,2)` -> `(2,2)`
*   `(3,2) @ (2,3)` -> `(3,3)`



In [11]:
# Element wise

print(f"{tensor} * {tensor} = {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


In [12]:
#Matrix multiplication

print(f"{tensor} * {tensor} = {torch.matmul(tensor,tensor)}")

tensor([1, 2, 3]) * tensor([1, 2, 3]) = 14


## Shape errors

In [13]:
tensor_A = torch.tensor([[1,2],
                                        [3,4],
                                        [5,6]])
tensor_B = torch.tensor([[7,8],
                                        [9,10],
                                        [11,12]])
# torch.matmul(tensor_A,tensor_B)

In [14]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix this issue we can manipulate on tensor by transposing.

A **transpose** switches the axis or the dimension of a given tensor.

In [15]:
tensor_B.T

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [16]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

## Finding the min,max,sum,etc of a tensor (tensor aggregations)

In [17]:
#Create a tesnor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [18]:
#Min
torch.min(x) #or x.min()

tensor(0)

In [19]:
#Max
torch.max(x) #or x.max()

tensor(90)

In [20]:
#Mean - works with either a floating point or complex dtype tensors
torch.mean(x.type(torch.float32)) #or x.mean() 

tensor(45.)

In [21]:
#Sum
torch.sum(x) # or x.sum()

tensor(450)

### Positional min and max

In [22]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [23]:
x.argmin()

tensor(0)

In [24]:
x.argmax()

tensor(9)

## Reshaping,squeezing,unsqueezing,stacking

*   Reshaping - reshapes input tensor -> defined shape
*   View - return view of input tensor of a certain shape but keep original in memory
*   Stacking - combine multiple tensors on top of each other(vstack) or side by side(hstack)
*   Squeeze - removes all `1-d` of a tensor
*   Unsqueeze - add a `1-d` to a tensor
*   Permute - retuen a view of the input tensor with dimensions permuted(swapped) in a certain way

In [25]:
import numpy as np
import pandas as pd
import torch

In [26]:
# create a tensor

y =torch.arange(1.,10.)
y , y.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [27]:
# reshaping
y_reshaped = y.reshape(1,9)
y_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [28]:
# view - the view shares the same memory as the original tensor;so any change to view changes the original tensor too

z=y.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [29]:
z[:,0] = 5
z,y

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [30]:
y_stacked = torch.stack([y,y,y,y],dim=1)
y_stacked.shape,y_stacked

(torch.Size([9, 4]),
 tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]))

Stacking also includes : 
*   `vstack()` -> https://pytorch.org/docs/stable/generated/torch.vstack.html
*   `hstack()` -> https://pytorch.org/docs/stable/generated/torch.hstack.html

Squeezing : `squeeze()` -> https://pytorch.org/docs/stable/generated/torch.squeeze.html

Unsqueezing : `unsqueeze()` -> https://pytorch.org/docs/stable/generated/torch.unsqueeze.html

In [31]:
print(f"Previous Tesnor : {y_reshaped}")
print(f"Previous shape : {y_reshaped.shape}")

y_squeezed = y_reshaped.squeeze()

print(f"Squeezed Tesnor : {y_squeezed}")
print(f"Squeezed shape : {y_squeezed.shape}")

Previous Tesnor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape : torch.Size([1, 9])
Squeezed Tesnor : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Squeezed shape : torch.Size([9])


In [32]:
print(f"Squeezed Tesnor : {y_squeezed}")
print(f"Squeezed shape : {y_squeezed.shape}")

y_unsqueezed = y_squeezed.unsqueeze(0)

print(f"Unsqueezed Tesnor : {y_unsqueezed}")
print(f"Unsqueezed shape : {y_unsqueezed.shape}")

Squeezed Tesnor : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Squeezed shape : torch.Size([9])
Unsqueezed Tesnor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Unsqueezed shape : torch.Size([1, 9])


In [33]:
x = torch.randn(2,3,5)
print(f"Original Tesnor : {x}")
print(f"Original Shape : {x.shape}")
x_permuted = torch.permute(x,(2,0,1))
print(f"Permuted Tesnor : {x_permuted}")
print(f"Permuted Shape : {x_permuted.shape}")

Original Tesnor : tensor([[[-0.1557,  1.6261,  0.0529,  1.6046, -0.5620],
         [ 1.1670,  2.0631, -1.3960, -0.0075, -0.8472],
         [ 0.3045, -0.5452, -0.0963,  1.2109,  0.4811]],

        [[-0.0595,  0.7402, -1.0113,  0.3686, -1.0070],
         [ 0.9568,  0.8356,  2.1948,  0.1332,  1.6283],
         [ 1.8992,  0.3304,  1.2352,  0.2367,  0.2727]]])
Original Shape : torch.Size([2, 3, 5])
Permuted Tesnor : tensor([[[-0.1557,  1.1670,  0.3045],
         [-0.0595,  0.9568,  1.8992]],

        [[ 1.6261,  2.0631, -0.5452],
         [ 0.7402,  0.8356,  0.3304]],

        [[ 0.0529, -1.3960, -0.0963],
         [-1.0113,  2.1948,  1.2352]],

        [[ 1.6046, -0.0075,  1.2109],
         [ 0.3686,  0.1332,  0.2367]],

        [[-0.5620, -0.8472,  0.4811],
         [-1.0070,  1.6283,  0.2727]]])
Permuted Shape : torch.Size([5, 2, 3])


## Pytorch and Numpy

**Pytorch and Numpy**
Numpy interactions possible using pytorch

*    Data in numpy -> Pytorch Tensor --> `torch.from_numpy(ndarray)`
*   Pytorch Tensor -> Numpy array --> `torch.Tensor.numpy()`

Note : When converting from numpy array -> torch tensor, torch reflects the array as a `float64` by default, unless specified otherwise

In [34]:
import numpy as np
import pandas as pd
import torch

In [35]:
# Numpy array => Tensor
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)

In [36]:
print(f"Array : {array}")
print(f"Type : {array.dtype}")
print(f" Tesnor : {tensor}")
print(f"Type : {tensor.dtype}")

Array : [1. 2. 3. 4. 5. 6. 7.]
Type : float64
 Tesnor : tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)
Type : torch.float64


In [37]:
new_tensor = torch.from_numpy(array).type(torch.float32)
print(f" Tesnor : {new_tensor}")
print(f"Type : {new_tensor.dtype}")

 Tesnor : tensor([1., 2., 3., 4., 5., 6., 7.])
Type : torch.float32


In [38]:
# Tensor => Numpy array
tensor = torch.ones(9)
numpy_tensor = torch.Tensor.numpy(tensor)
print(f"Tesnor : {tensor}")
print(f"Type : {tensor.dtype}")
print(f"Array : {numpy_tensor}")
print(f"Type : {numpy_tensor.dtype}")

Tesnor : tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.])
Type : torch.float32
Array : [1. 1. 1. 1. 1. 1. 1. 1. 1.]
Type : float32


## Reproducbility ( trying to take out the random out of random)

`start with random numbers -> tensor operations -> update random numbers to try and better represent the data -> repeat`

To reduce randomness in neural networks, we use the concept of **random seed**.


In [39]:
import torch
import numpy

In [40]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8428, 0.6361, 0.8934, 0.8766],
        [0.5024, 0.7602, 0.7362, 0.2586],
        [0.2924, 0.3444, 0.3856, 0.4952]])
tensor([[0.7755, 0.7447, 0.7318, 0.4161],
        [0.8641, 0.0188, 0.3331, 0.5454],
        [0.0358, 0.6248, 0.5172, 0.1900]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [41]:
#Making reproducible tensors

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [42]:
#Still not the desired result as it requires seed to be set after each method as it has subsequent methods

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_E = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_F = torch.rand(3,4)

print(random_tensor_E)
print(random_tensor_F)
print(random_tensor_E == random_tensor_F)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


For more information about reproducibility -> https://pytorch.org/docs/stable/notes/randomness.html

## Running Tensors and PyTorch objects on the GPUs (for faster computations)

### 1. Getting a GPU

Methods :
1. Easiest - Google Colab
2. Own GPU - requires set up and investment . (can be selected -> https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/)
3. Cloud computing - GCP,AWS,Azure etc.

For 2 -> https://pytorch.org/get-started/cloud-partners/

For 3 -> https://pytorch.org/get-started/cloud-partners/


In [43]:
!nvidia-smi

Sun May 28 13:17:14 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   51C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 2. Check for GPU access 

-> https://pytorch.org/docs/stable/notes/cuda.html

In [44]:
# Check access using `is_available()`
import torch
torch.cuda.is_available()

True

In [45]:
# Setting up device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [46]:
# Counting no of devices
torch.cuda.device_count()

1

## 3. Putting tensors(or models) on the GPU

In [47]:
# Creating a tensor
tensor  = torch.Tensor([1,2,3])

#Checking tensor and device property
print(tensor,tensor.device)

tensor([1., 2., 3.]) cpu


In [48]:
# Moving tensor to gpu
tensor_on_gpu = tensor.to(device)

#Checking tensor and device property
print(tensor_on_gpu,tensor_on_gpu.device)

tensor([1., 2., 3.], device='cuda:0') cuda:0


## 4. Moving tensors back to CPU

In [49]:
# Not having the tensors on the right device, can result in errors

#tensor_on_gpu.numpy()
# above line gives an error as numpy() needs tensors on the cpu

In [50]:
# back to cpu using `.cpu()`
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
print(tensor_back_on_cpu)

[1. 2. 3.]
